add_newline = false

format = """\
    $time\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $docker_context\
    $dotnet\
    $conda\
    $env_var\
    $line_break\
    $jobs\
    $battery\
    $cmd_duration\
    $character\
"""

[directory]
style = "blue"

[character]
success_symbol = "[;](blue)"
error_symbol = "[;](green)"

[python]
symbol = ""

[conda]
symbol = ""
style = "blue"

[line_break]
disabled = true

[git_branch]
symbol = ""
style = "blue"

[jobs]
symbol = "+"

