add_newline = true

[character]
symbol = "Î»"

[python]
symbol = "py::"

[conda]
symbol = ""

[rust]
symbol = "rust::"

[golang]
symbol = "go::"

[nodejs]
symbol = "node::"

[package]
symbol = "pkg::"

[java]
symbol = "java::"

[ruby]
symbol = "ruby::"

[line_break]
disabled = false
