set black 000000
set white ffffff
set grey  777777

set fish_color_normal $white
set fish_color_command $white
set fish_color_quote $white
set fish_color_redirection $white
set fish_color_end $white
set fish_color_error $white
set fish_color_param $white
set fish_color_comment $white
set fish_color_match $white
set fish_color_search_match $white
set fish_color_operator $white
set fish_color_escape $white
set fish_color_cwd $white
set fish_color_autosuggestion $grey
set fish_color_user $white
set fish_color_host $white
set fish_color_cancel $white
set fish_pager_color_prefix $white
set fish_pager_color_completion $white
set fish_pager_color_description $white
set fish_pager_color_progress $white
set fish_pager_color_secondary $white
