set blue    7099c2
set cyan    70c2bb
set green   70c299
set red     c2708b
set white   d9d9d9
set black   242528
set yellow  bdc270
set grey    888888
set orange  c28570
set purple  a770c2

set fish_color_normal $white
set fish_color_command $red
set fish_color_quote $green
set fish_color_redirection $cyan
set fish_color_end $red
set fish_color_error $red
set fish_color_param $red
set fish_color_comment $grey
set fish_color_match $blue
set fish_color_search_match $red
set fish_color_operator $red
set fish_color_escape $red
set fish_color_cwd $red
set fish_color_autosuggestion $grey
set fish_color_user $red
set fish_color_host $red
set fish_color_cancel $red
set fish_pager_color_prefix $red
set fish_pager_color_completion $red
set fish_pager_color_description $red
set fish_pager_color_progress $red
set fish_pager_color_secondary $red
